add api test in action

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -16,3 +16,13 @@ jobs:
     - uses: actions/checkout@v4
     - name: Build the Docker image
       run: docker build . --file Dockerfile --tag python-app:$(date +%s)
+
+    - name: Call /version endpoint
+      run: |
+          response=$(curl -s http://localhost:5000/version)
+          echo "Response from /version: $response"
+          if [[ "$response" != "Current app version: 1.0.0" ]]; then
+            echo "Version check failed!"
+            exit 1
+          fi
+    
