add api test in action

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -26,7 +26,11 @@ jobs:
 
     - name: Call /version endpoint
       run: |
+          sleep 60
           response=$(curl -s http://localhost:5000/version)
           echo "Response from /version: $response"
-          
+          if [[ "$response" != "Current app version: 1.0.0" ]]; then
+            echo "Version check failed!"
+            exit 1
+          fi
     
